import React, { useMemo, useState } from 'react'
import { Badge, Card, PageHead, formatWon, formatNum } from '../components.jsx'
import { SIGUN, getOpenArrears } from '../data.js'

const PER_PAGE=30
export default function ReceivablesList({data,preset,setPreset,saveMemo,applyPayment,registerClosure}){
  const [q,setQ]=useState(preset?.q||''); const [sigun,setSigun]=useState(preset?.sigun||'전체'); const [memberType,setMemberType]=useState('전체'); const [membership,setMembership]=useState('전체'); const [amount,setAmount]=useState(preset?.amount||'미수있음'); const [status,setStatus]=useState('정상'); const [special,setSpecial]=useState(preset?.special||''); const [selected,setSelected]=useState(null); const [page,setPage]=useState(1)
  React.useEffect(()=>{ if(preset){setQ(preset.q||''); setSigun(preset.sigun||'전체'); setAmount(preset.amount||'미수있음'); setSpecial(preset.special||''); setPage(1); setPreset?.(null)}},[preset])
  const rows=useMemo(()=>{
    let arr=[...data.members]
    if(status!=='전체') arr=arr.filter(m=>m.status===status)
    if(amount==='미수있음') arr=arr.filter(m=>m.totalArrears>0)
    if(amount==='완납') arr=arr.filter(m=>m.totalArrears===0)
    if(amount==='30만원이상') arr=arr.filter(m=>m.totalArrears>=300000)
    if(sigun!=='전체') arr=arr.filter(m=>m.sigun===sigun)
    if(memberType!=='전체') arr=arr.filter(m=>m.memberType===memberType)
    if(membership!=='전체') arr=arr.filter(m=>m.membership===membership)
    if(special==='장기') arr=arr.filter(m=>m.arrearsMonths>=12)
    if(special==='결번') arr=arr.filter(m=>m.disconnected)
    if(special==='자격') arr=arr.filter(m=>m.certMissing)
    if(q.trim()){const s=q.trim().toLowerCase(); arr=arr.filter(m=>[m.name,m.vehicleNo,m.mgmtNo,m.phone,m.regionRaw].join(' ').toLowerCase().includes(s))}
    return arr.sort((a,b)=>b.totalArrears-a.totalArrears)
  },[data.members,q,sigun,memberType,membership,amount,status,special])
  const pages=Math.max(1,Math.ceil(rows.length/PER_PAGE)); const pageRows=rows.slice((page-1)*PER_PAGE,page*PER_PAGE)
  function exportCSV(){const head=['지역','이름','차량번호','회원구분','가입여부','관리번호','부과구분','미수월수','미납금액','마지막납부월','연락처','상태','메모']; const lines=[head.join(',')].concat(rows.map(m=>[m.sigun,m.name,m.vehicleNo,m.memberType,m.membership,m.mgmtNo,m.chargeItem,m.arrearsMonths,m.totalArrears,m.lastPaymentYm,m.phone,m.status,(m.memo||'').replaceAll(',',' ')].join(','))); const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv;charset=utf-8'})); a.download='미수금명단.csv'; a.click()}
  return <div>
    <PageHead title="미수금명단 (MAIN)" desc="회원정보 · 부과기준 · 미수상세 · 수납반영 · 폐업등록을 한 화면에서 처리합니다."><button className="btn" onClick={()=>{setQ('');setSigun('전체');setMemberType('전체');setMembership('전체');setAmount('미수있음');setStatus('정상');setSpecial('')}}>필터 초기화</button><button className="btn soft" onClick={exportCSV}>엑셀 다운로드</button></PageHead>
    <div className="grid grid-4" style={{marginBottom:14}}><Card className="stat"><div className="stat-label">검색 결과</div><div className="stat-value">{formatNum(rows.length)}명</div></Card><Card className="stat"><div className="stat-label">미수금 합계</div><div className="stat-value" style={{color:'var(--red)'}}>{formatWon(rows.reduce((s,m)=>s+m.totalArrears,0))}</div></Card><Card className="stat"><div className="stat-label">30만원 이상</div><div className="stat-value" style={{color:'var(--orange)'}}>{formatNum(rows.filter(m=>m.totalArrears>=300000).length)}명</div></Card><Card className="stat"><div className="stat-label">장기 미납</div><div className="stat-value" style={{color:'var(--purple)'}}>{formatNum(rows.filter(m=>m.arrearsMonths>=12).length)}명</div></Card></div>
    <Card className="card-pad" style={{marginBottom:14}}><div className="filters"><input className="input" value={q} onChange={e=>setQ(e.target.value)} placeholder="이름 · 차량번호 · 관리번호 · 연락처 검색"/><select className="select" value={sigun} onChange={e=>setSigun(e.target.value)}><option>전체</option>{SIGUN.map(s=><option key={s}>{s}</option>)}</select><select className="select" value={memberType} onChange={e=>setMemberType(e.target.value)}><option>전체</option><option>개인</option><option>택배</option></select><select className="select" value={membership} onChange={e=>setMembership(e.target.value)}><option>전체</option><option>협회가입</option><option>협회미가입</option></select><select className="select" value={amount} onChange={e=>setAmount(e.target.value)}><option>미수있음</option><option>완납</option><option>전체</option><option>30만원이상</option></select><select className="select" value={status} onChange={e=>setStatus(e.target.value)}><option>정상</option><option>전체</option><option>폐업</option><option>양도</option><option>이관</option><option>탈퇴</option></select></div><div style={{marginTop:10}} className="tabs"><button className={'chip '+(special==='장기'?'active':'')} onClick={()=>setSpecial(special==='장기'?'':'장기')}>장기미납 12개월↑</button><button className={'chip '+(special==='결번'?'active':'')} onClick={()=>setSpecial(special==='결번'?'':'결번')}>결번/반송</button><button className={'chip '+(special==='자격'?'active':'')} onClick={()=>setSpecial(special==='자격'?'':'자격')}>자격증명 미발급</button></div></Card>
    <Card><div className="table-wrap"><table className="table"><thead><tr><th>지역</th><th>이름</th><th>차량번호</th><th>회원구분</th><th>가입여부</th><th>관리번호</th><th>부과구분</th><th className="right">미수월수</th><th className="right">미납금액</th><th>마지막 납부월</th><th>연락처</th><th>상태</th><th>메모</th><th className="right">처리</th></tr></thead><tbody>{pageRows.map(m=><tr key={m.id} onClick={()=>setSelected(m)}><td>{m.sigun}</td><td><b>{m.name}</b> {m.age>=70&&<Badge tone="purple">70↑</Badge>}</td><td className="mono">{m.vehicleNo}</td><td><Badge tone={m.memberType==='택배'?'orange':'gray'}>{m.memberType}</Badge></td><td><Badge tone={m.membership==='협회가입'?'blue':'gray'}>{m.membership}</Badge></td><td className="mono">{m.mgmtNo}</td><td><Badge tone={m.chargeItem==='협회비'?'blue':'green'}>{m.chargeItem}</Badge></td><td className="right"><b>{m.arrearsMonths}</b></td><td className="right money" style={{color:m.totalArrears>=300000?'var(--red)':undefined}}>{formatWon(m.totalArrears)}</td><td>{m.lastPaymentYm}</td><td className="mono" style={{color:m.disconnected?'var(--red)':undefined}}>{m.phone}</td><td><Badge tone={m.status==='정상'?'green':'red'}>{m.status}</Badge></td><td style={{maxWidth:180,whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}}>{m.memo}</td><td className="right"><button className="btn soft" onClick={(e)=>{e.stopPropagation();setSelected(m)}}>열기</button></td></tr>)}{!pageRows.length&&<tr><td colSpan="14" style={{textAlign:'center',padding:40,color:'var(--sub)'}}>조건에 맞는 회원이 없습니다.</td></tr>}</tbody></table></div><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',padding:12,borderTop:'1px solid var(--line)'}}><span className="small">{formatNum(rows.length)}명 중 {formatNum((page-1)*PER_PAGE+1)}–{formatNum(Math.min(page*PER_PAGE,rows.length))}</span><div><button className="btn" disabled={page<=1} onClick={()=>setPage(page-1)}>이전</button> <b>{page}/{pages}</b> <button className="btn" disabled={page>=pages} onClick={()=>setPage(page+1)}>다음</button></div></div></Card>
    {selected&&<MemberDrawer member={data.members.find(m=>m.id===selected.id)||selected} onClose={()=>setSelected(null)} saveMemo={saveMemo} applyPayment={applyPayment} registerClosure={registerClosure}/>}  </div>
}
function MemberDrawer({member,onClose,saveMemo,applyPayment,registerClosure}){const [memo,setMemo]=useState(member.memo||''); const [pay,setPay]=useState(false); const [close,setClose]=useState(false); const open=getOpenArrears(member); return <div className="drawer-bg" onMouseDown={onClose}><div className="drawer" onMouseDown={e=>e.stopPropagation()}><div className="drawer-head"><div><h2 style={{margin:0}}>{member.name} <span className="mono">{member.vehicleNo}</span></h2><div className="page-desc">{member.sigun} · {member.mgmtNo} · {member.memberType}/{member.membership}</div></div><button className="btn" onClick={onClose}>닫기</button></div><div className="notice">폐업 처리 시 미수금명단에서는 제외됩니다. 미수금이 없어도 처리 내용은 입력해야 하며, 미수금이 남아 있으면 추후 납부 안내 대상으로 남습니다.</div><div className="section-title">회원 기본정보</div><div className="info-grid"><Info k="연락처" v={member.phone}/><Info k="상태" v={member.status}/><Info k="자격증명 발급일" v={member.certIssueDate}/><Info k="협회 가입일" v={member.assocJoinDate||'-'}/><Info k="부과 시작월" v={member.billingStartYm}/><Info k="부과금액" v={`${member.chargeItem} ${formatWon(member.monthlyCharge)}`}/></div><div className="section-title">미수 상세</div><Card><div className="table-wrap"><table className="table" style={{minWidth:520}}><thead><tr><th>미수월</th><th>항목</th><th className="right">금액</th><th>상태</th></tr></thead><tbody>{open.map(a=><tr key={a.ym}><td>{a.label}</td><td>{a.item}</td><td className="right">{formatWon(a.amount)}</td><td><Badge tone="red">미납</Badge></td></tr>)}{!open.length&&<tr><td colSpan="4" style={{textAlign:'center',padding:24,color:'var(--sub)'}}>미수금 없음</td></tr>}</tbody></table></div></Card><div className="section-title">메모</div><textarea className="textarea" value={memo} onChange={e=>setMemo(e.target.value)} /><div style={{display:'flex',gap:8,marginTop:12}}><button className="btn primary" onClick={()=>saveMemo(member.id,memo)}>메모 저장</button><button className="btn green" onClick={()=>setPay(true)}>수납 반영</button><button className="btn red" onClick={()=>setClose(true)}>폐업 등록</button></div><div className="section-title">수정이력</div><div className="small">최근 수정: {member.updatedAt} · 실제 DB 연결 시 처리자/시간/변경 전후값 저장</div>{pay&&<PaymentModal member={member} onClose={()=>setPay(false)} onSave={(amt)=>{applyPayment(member.id,amt); setPay(false)}}/>}{close&&<ClosureModal member={member} onClose={()=>setClose(false)} onSave={(p)=>{registerClosure(member.id,p); setClose(false); onClose()}}/>}</div></div>}
function Info({k,v}){return <div className="info"><b>{k}</b><span>{v}</span></div>}
function PaymentModal({member,onClose,onSave}){const [amount,setAmount]=useState(member.monthlyCharge); return <div className="modal-bg"><div className="modal"><h3>수납 반영</h3><div className="form-row"><b>대상</b><span>{member.name} / {member.vehicleNo}</span></div><div className="form-row"><b>입금액</b><input className="input" type="number" value={amount} onChange={e=>setAmount(e.target.value)}/></div><div className="notice">오래된 미수월부터 금액만큼 차감됩니다.</div><div style={{display:'flex',justifyContent:'flex-end',gap:8,marginTop:16}}><button className="btn" onClick={onClose}>취소</button><button className="btn green" onClick={()=>onSave(Number(amount))}>저장</button></div></div></div>}
function ClosureModal({member,onClose,onSave}){const [type,setType]=useState('폐업'); const [docNo,setDocNo]=useState(''); const [content,setContent]=useState('시청 폐업공문 접수 후 처리'); return <div className="modal-bg"><div className="modal"><h3>폐업/이탈 등록</h3><div className="form-row"><b>처리사유</b><select className="select" value={type} onChange={e=>setType(e.target.value)}><option>폐업</option><option>탈퇴</option><option>양도</option><option>이관</option></select></div><div className="form-row"><b>공문번호</b><input className="input" value={docNo} onChange={e=>setDocNo(e.target.value)} placeholder="공문번호 또는 접수번호"/></div><div className="form-row"><b>내용</b><textarea className="textarea" value={content} onChange={e=>setContent(e.target.value)}/></div><div className="notice">미수금 현재 잔액: {formatWon(member.totalArrears)}. 폐업 처리 후 명단에서는 제외되며, 잔액이 있으면 추후 납부 안내 대상입니다.</div><div style={{display:'flex',justifyContent:'flex-end',gap:8,marginTop:16}}><button className="btn" onClick={onClose}>취소</button><button className="btn red" onClick={()=>onSave({type,docNo,content})}>처리 저장</button></div></div></div>}
